version: "3.8"
services:
  db:
    image: postgres:18
    env_file:
      - ../../app/back/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - herokoou_db:/var/lib/postgresql

volumes:
  herokoou_db:
